---
title: "Make and model data in STATS19"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Make and model data in STATS19}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r setup}
# install.packages("stats19")
install.packages("purrr")
install.packages("dplyr")
install.packages("tidyverse")
library(stats19)
library(purrr)
library(dplyr)
library('tidyverse')
```

# Make and model data

```{r}
# Request data for all years. Approximately 1.6GB
target_file <- "dft-road-casualty-statistics-vehicle-1979-latest-published-year.csv"
```

```{r}
# Get our dataset
data <- get_stats19(
  type = "vehicle",
  filename = target_file
) 
```

```{r}
presence_table <- data |>
  select(year = collision_year, make_model = generic_make_model) |>
  filter(!is.na(make_model)) |>
  distinct() |>
  mutate(present = 1) |>
  pivot_wider(
   names_from = year,
    values_from = present,
    values_fill = 0,
   names_sort = TRUE
  ) |>
  arrange(make_model)
```

```{r}
glimpse(presence_table)
```